{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  airflow.cfg: |-
  {{- if .Values.configuration }}
    {{- include "common.tplvalues.render" (dict "value" .Values.configuration "context" .) }}
  {{- else }}
    [core]
    load_examples={{ ternary "True" "False" .Values.loadExamples }}
    executor={{ .Values.executor }}

    [logging]
    colored_console_log=False

    [scheduler]
    standalone_dag_processor={{ ternary "True" "False" .Values.dagProcessor.enabled }}

    [triggerer]
    default_capacity={{ .Values.triggerer.defaultCapacity }}

    [webserver]
    base_url={{ include "airflow.baseUrl" . }}
    enable_proxy_fix={{ ternary "True" "False" (and .Values.ingress.enabled .Values.ingress.tls) }}
    web_server_port={{ .Values.web.containerPorts.http}}
  {{- if .Values.web.tls.enabled }}
    web_server_ssl_cert="/opt/bitnami/airflow/certs/tls.crt"
    web_server_ssl_key="/opt/bitnami/airflow/certs/tls.key"
  {{- end }}

  {{- if contains "KubernetesExecutor" .Values.executor }}
    [kubernetes_executor]
    namespace={{ include "common.names.namespace" . }}
    worker_container_repository={{ printf "%s/%s" .Values.image.registry .Values.image.repository }}
    worker_container_tag={{ .Values.image.tag }}
    delete_worker_pods=True
    delete_worker_pods_on_failure=True
    pod_template_file="/opt/bitnami/airflow/pod_template.yaml"
  {{- end }}
  {{- end }}
{{- end }}
